spring:
  application:
    name: ORDER-SERVICE

server:
  port: 9005

eureka:
  instance:
    appname: ORDER-SERVICE
  client:
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka