spring:
  application:
    name: USER-SERVICE

eureka:
  instance:
    appname: USER-SERVICE
  client:
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka

server:
  port: 9001