server:
  port: 9000

spring:
  application:
    name: zuul-server

zuul:
  prefix: /api-gateway
  routes:
    resources:
    USER-SERVICE:
      path: /api-user/**
      serviceId: USER-SERVICE
    ORDER-SERVICE:
      path: /api-order/**
      serviceId: ORDER-SERVICE

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka
